export const PHRASE_STATUS = {
  AVAILABLE: 'available',
  EXPIRED: 'expired',
  RENDERING: 'rendering',
  PENDING: 'pending',
}

export const PLAYHEAD_STATE = {
  PLAYING: 'playing',
  WAITING: 'waiting',
  STOPPED: 'stopped',
}

export const RENDER_PRIORITY = {
  URGENT: 1,
  VISIBLE: 2,
  BACKGROUND: 3,
}

export const EVENTS = {
  MIDI_LOADED: 'midi:loaded',
  USTX_LOADED: 'ustx:loaded',
  USTX_EXPORT: 'ustx:export',
  TRACK_SELECTED: 'track:selected',
  TRANSPORT_PLAY: 'transport:play',
  TRANSPORT_PAUSE: 'transport:pause',
  TRANSPORT_STOP: 'transport:stop',
  TRANSPORT_SEEK: 'transport:seek',
  TRANSPORT_SEEK_UPDATE: 'transport:seek-update',
  TRANSPORT_TICK: 'transport:tick',
  CACHE_HIT: 'cache:hit',
  CACHE_MISS: 'cache:miss',
  CACHE_INVALIDATED: 'cache:invalidated',
  CACHE_UPDATED: 'cache:updated',
  RENDER_COMPLETE: 'render:complete',
  RENDER_PRIORITIZE: 'render:prioritize',
  RENDER_PROGRESS: 'render:progress',
  PHRASES_UPDATED: 'phrases:updated',
  PHRASE_MODIFIED: 'phrase:modified',
  JOB_SUBMITTED: 'job:submitted',
  JOB_PROGRESS: 'job:progress',
  JOB_FAILED: 'job:failed',
  PLAYBACK_PROGRESS: 'playback:progress',
  PLAYBACK_PHRASE_END: 'playback:phrase-end',
  PLAYHEAD_WAITING: 'playhead:waiting',
  PLAYHEAD_RESUMED: 'playhead:resumed',
  PHRASES_REBUILT: 'phrases:rebuilt',
  PHRASES_EDITED: 'phrases:edited',
  NOTE_SELECTION_CHANGED: 'note-selection-changed',
  PITCH_LOADED: 'pitch:loaded',
  PITCH_CHANGED: 'pitch:changed',
  PITCH_EDITOR_MODE_CHANGED: 'pitch:editor-mode-changed',
  PITCH_EDITOR_SELECTION_CHANGED: 'pitch:editor-selection-changed',
  PREDICTION_READY: 'prediction:ready',
}

export const JOB_STATUS = {
  QUEUED: 'queued',
  PREPARING: 'preparing',
  RENDERING: 'rendering',
  COMPLETED: 'completed',
  FAILED: 'failed',
}

export const PIANO_ROLL = {
  PITCH_MIN: 36,
  PITCH_MAX: 84,
  KEY_HEIGHT: 20,
  KEYBOARD_WIDTH: 48,
  PIXELS_PER_SECOND: 300,
  MIN_PPS: 10,
  MAX_PPS: 800,
  GRID_MIN_GAP_PX: 12,
  TIME_RULER_HEIGHT: 24,
  TIME_RULER_BG: '#F4F2EC',
  TIME_RULER_TEXT_COLOR: '#7A766F',
  TIME_RULER_TICK_COLOR: '#A3A097',
  TIME_RULER_FONT: '10px "JetBrains Mono", monospace',
  DEFAULT_BPM: 120,
  DEFAULT_TIME_SIGNATURE: [4, 4],
  BAR_LINE_WIDTH: 1.5,
  AUTO_SCROLL_PADDING: 50,
  KEYBOARD_BLACK_WIDTH_RATIO: 0.6,
  NOTE_CORNER_RADIUS: 3,
  NOTE_VERTICAL_OFFSET: 1,
  NOTE_VERTICAL_GAP: 2,
  NOTE_BORDER_DARKEN_RATIO: 0.2,
  BLACK_KEY_PITCHES: [1, 3, 6, 8, 10],
  WHITE_KEY_COLOR: '#F8F5EE',
  BLACK_KEY_COLOR: '#E7E2D9',
  GRID_LINE_COLOR: 'rgba(43, 40, 37, 0.08)',
  BAR_LINE_COLOR: '#A3A097',
  KEY_LABEL_COLOR: '#5F5A53',
  KEY_BORDER_COLOR: '#BBB5AA',
  NOTE_COLOR_PENDING: '#8F8A80',
  NOTE_COLOR_RENDERING: '#B8862D',
  NOTE_COLOR_AVAILABLE: '#3B8B88',
  NOTE_COLOR_EXPIRED: '#8D746E',
  PITCH_LINE_COLOR: 'rgba(201, 66, 52, 0.78)',
  PITCH_LINE_WIDTH: 1.5,
  PITCH_BASE_LINE_COLOR: 'rgba(95, 90, 83, 0.3)',
  PITCH_POINT_COLOR: '#f5ede0',
  PITCH_POINT_ACTIVE_COLOR: '#c94234',
  PITCH_POINT_RADIUS: 4,
  PITCH_POINT_HIT_RADIUS: 8,
  PHONEME_TIMING_HEIGHT: 76,
  PHONEME_TIMING_MIN_PPS: 110,
  PHONEME_TIMING: {
    BG: '#E1DDD4',
    PANEL_BG: '#ECE8DE',
    BORDER: '#8F8A80',
    GRID_LIGHT: '#D6D1C4',
    GRID_DARK: '#BDB7A9',
    FILL: 'rgba(59, 139, 136, 0.45)',
    STROKE: '#3B8B88',
    ATTACK: '#C94234',
    TEXT: '#2B2825',
    MUTED: '#666158',
  },
}
