function createPreset(id, name, description, config, tags = []) {
  return Object.freeze({
    id,
    name,
    description,
    tags: Object.freeze([...tags]),
    config: Object.freeze({
      decaySec: config.decaySec,
      decayCurve: config.decayCurve,
      preDelaySec: config.preDelaySec,
      lowCutHz: config.lowCutHz,
      highCutHz: config.highCutHz,
      returnGain: config.returnGain,
    }),
  })
}

export const REVERB_PRESET_CATALOG = Object.freeze({
  'zita-vocal-default': createPreset(
    'zita-vocal-default',
    'Vocal Default',
    'Balanced hall-style vocal reverb.',
    {
      decaySec: 2.4,
      decayCurve: 2.2,
      preDelaySec: 0.028,
      lowCutHz: 180,
      highCutHz: 7200,
      returnGain: 0.9,
    },
    ['vocal', 'hall'],
  ),
  'zita-room-tight': createPreset(
    'zita-room-tight',
    'Room Tight',
    'Short room with quick decay for close vocals.',
    {
      decaySec: 0.9,
      decayCurve: 1.8,
      preDelaySec: 0.012,
      lowCutHz: 240,
      highCutHz: 6800,
      returnGain: 0.82,
    },
    ['room', 'vocal'],
  ),
  'zita-plate-bright': createPreset(
    'zita-plate-bright',
    'Plate Bright',
    'Bright plate-like tail with minimal pre-delay.',
    {
      decaySec: 2.0,
      decayCurve: 1.6,
      preDelaySec: 0.006,
      lowCutHz: 160,
      highCutHz: 12000,
      returnGain: 0.95,
    },
    ['plate', 'vocal'],
  ),
  'zita-hall-airy': createPreset(
    'zita-hall-airy',
    'Hall Airy',
    'Large airy hall for open vocal space.',
    {
      decaySec: 3.2,
      decayCurve: 2.3,
      preDelaySec: 0.035,
      lowCutHz: 140,
      highCutHz: 9000,
      returnGain: 0.92,
    },
    ['hall', 'vocal'],
  ),
  'zita-church-wide': createPreset(
    'zita-church-wide',
    'Church Wide',
    'Long and wide church-style ambience.',
    {
      decaySec: 5.8,
      decayCurve: 2.8,
      preDelaySec: 0.055,
      lowCutHz: 120,
      highCutHz: 7600,
      returnGain: 1.0,
    },
    ['church', 'hall'],
  ),
  'zita-bathroom-short': createPreset(
    'zita-bathroom-short',
    'Bathroom Short',
    'Hard-surface short reverb for compact reflections.',
    {
      decaySec: 0.55,
      decayCurve: 1.3,
      preDelaySec: 0.004,
      lowCutHz: 300,
      highCutHz: 10500,
      returnGain: 0.78,
    },
    ['bathroom', 'room'],
  ),
  'zita-vocal-dark': createPreset(
    'zita-vocal-dark',
    'Vocal Dark',
    'Darker hall tail to control sibilance.',
    {
      decaySec: 2.8,
      decayCurve: 2.5,
      preDelaySec: 0.022,
      lowCutHz: 210,
      highCutHz: 5200,
      returnGain: 0.88,
    },
    ['vocal', 'hall', 'dark'],
  ),
  'zita-drum-room-punch': createPreset(
    'zita-drum-room-punch',
    'Drum Room Punch',
    'Short energetic room for percussive sources.',
    {
      decaySec: 1.1,
      decayCurve: 1.5,
      preDelaySec: 0.009,
      lowCutHz: 260,
      highCutHz: 7800,
      returnGain: 0.84,
    },
    ['drum', 'room'],
  ),
  'zita-spring-color': createPreset(
    'zita-spring-color',
    'Spring Color',
    'Colored vintage-style spring-like ambience.',
    {
      decaySec: 1.6,
      decayCurve: 1.2,
      preDelaySec: 0.003,
      lowCutHz: 220,
      highCutHz: 6800,
      returnGain: 0.86,
    },
    ['spring', 'color'],
  ),
})
